[autoexec]
MOUNT C C:\8086
C:
cls
ECHO 8086 ASSEMBLY...
masm.exe ASMFiles\FIRSTPRO.ASM built\FIRSTPRO\FIRSTPRO built\FIRSTPRO\FIRSTPRO built\FIRSTPRO\FIRSTPRO;
link.exe built\FIRSTPRO\FIRSTPRO.obj built\FIRSTPRO\FIRSTPRO;
FIRSTPRO.exe
pause
exit
